jobs:
  ci:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./ci/run

name: Build

on:
  schedule:
    - cron: "5 */6 * * *"
